name: Polls
version: '1.0'
main: net.norius.polls.Polls
api-version: '1.21'
authors: [ Norius ]
description: Create Custom Polls

permissions:
  polls.createpoll:
    description: "Allows creating a poll"
  polls.remove:
    description: "Allows removing a poll"
  polls.close:
    description: "Allows closing a poll"
  polls.ended:
    description: "Allows viewing the ended polls"

commands:
  createpoll:
    description: "Creates a poll"
    permission: "polls.createpoll"
  poll:
    description: "Opens a menu where you can find active polls"
  endedpolls:
    description: "Shows the ended polls"
    permission: "polls.ended"
